#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProtocolRules {
    pub version: u32,
    pub shielded_pool_version: u8,
    pub genesis_difficulty: u32,
    pub genesis_mem_kib: u32,
    pub retarget_interval: u64,
    pub target_coins_per_epoch: u64,
    pub max_coins_per_epoch: u32,
    pub nullifier_epoch_length: u64,
    pub max_historical_nullifier_batch: u32,
    pub archive_shard_epoch_span: u64,
    pub archive_provider_replica_count: u32,
    pub archive_segment_target_providers: u32,
    pub archive_checkpoint_packet_segments: u32,
    pub archive_retention_horizon_epochs: u64,
    pub oblivious_sync_min_batch: u32,
    pub oblivious_sync_refresh_interval_secs: u64,
    pub oblivious_sync_cover_queries: u32,
    pub difficulty_min: u32,
    pub difficulty_max: u32,
    pub min_mem_kib: u32,
    pub max_mem_kib: u32,
    pub retarget_upper_pct: u64,
    pub retarget_lower_pct: u64,
}

pub const CURRENT: ProtocolRules = ProtocolRules {
    version: 1,
    shielded_pool_version: 1,
    genesis_difficulty: 2,
    genesis_mem_kib: 16_192,
    retarget_interval: 2000,
    target_coins_per_epoch: 11,
    max_coins_per_epoch: 111,
    nullifier_epoch_length: 32,
    max_historical_nullifier_batch: 512,
    archive_shard_epoch_span: 16,
    archive_provider_replica_count: 4,
    archive_segment_target_providers: 3,
    archive_checkpoint_packet_segments: 4,
    archive_retention_horizon_epochs: 256,
    oblivious_sync_min_batch: 4,
    oblivious_sync_refresh_interval_secs: 300,
    oblivious_sync_cover_queries: 4,
    difficulty_min: 1,
    difficulty_max: 12,
    min_mem_kib: 16_192,
    max_mem_kib: 512_007,
    retarget_upper_pct: 110,
    retarget_lower_pct: 90,
};
