#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProtocolRules {
    pub version: u32,
    pub shielded_pool_version: u8,
    pub max_active_validators: u16,
    pub slots_per_epoch: u32,
    pub slot_duration_ms: u64,
    pub fast_path_timeout_ms: u64,
    pub dag_bft_timeout_ms: u64,
    pub stake_unbonding_epochs: u64,
    pub equivocation_slash_bps: u16,
    pub equivocation_jail_epochs: u64,
    pub equivocation_retirement_faults: u32,
    pub liveness_fault_slash_bps: u16,
    pub liveness_fault_jail_threshold: u32,
    pub liveness_fault_jail_epochs: u64,
    pub liveness_fault_retirement_faults: u32,
    pub ordinary_private_transfer_fee: u64,
    pub private_delegation_fee: u64,
    pub private_undelegation_fee: u64,
    pub unbonding_claim_fee: u64,
    pub validator_registration_fee: u64,
    pub validator_profile_update_fee: u64,
    pub penalty_evidence_admission_fee: u64,
    pub validator_reactivation_fee: u64,
    pub validator_reward_bps_per_anchor: u16,
    pub minimum_validator_reward_per_anchor: u64,
    pub max_coins_per_epoch: u32,
    pub max_shared_state_txs_per_checkpoint: u32,
    pub nullifier_epoch_length: u64,
    pub max_historical_nullifier_batch: u32,
    pub archive_shard_epoch_span: u64,
    pub archive_provider_replica_count: u32,
    pub archive_segment_target_providers: u32,
    pub archive_checkpoint_packet_segments: u32,
    pub archive_checkpoint_stratum_packets: u32,
    pub archive_retention_horizon_epochs: u64,
    pub oblivious_sync_min_batch: u32,
    pub oblivious_sync_refresh_interval_secs: u64,
    pub oblivious_sync_cover_queries: u32,
}

pub const CURRENT: ProtocolRules = ProtocolRules {
    version: 1,
    shielded_pool_version: 1,
    max_active_validators: 32,
    slots_per_epoch: 256,
    slot_duration_ms: 250,
    fast_path_timeout_ms: 450,
    dag_bft_timeout_ms: 10_000,
    stake_unbonding_epochs: 32,
    equivocation_slash_bps: 2_500,
    equivocation_jail_epochs: 8,
    equivocation_retirement_faults: 2,
    liveness_fault_slash_bps: 25,
    liveness_fault_jail_threshold: 3,
    liveness_fault_jail_epochs: 2,
    liveness_fault_retirement_faults: 9,
    ordinary_private_transfer_fee: 1,
    private_delegation_fee: 1,
    private_undelegation_fee: 1,
    unbonding_claim_fee: 1,
    validator_registration_fee: 1,
    validator_profile_update_fee: 1,
    penalty_evidence_admission_fee: 1,
    validator_reactivation_fee: 1,
    validator_reward_bps_per_anchor: 1,
    minimum_validator_reward_per_anchor: 1,
    max_coins_per_epoch: 111,
    max_shared_state_txs_per_checkpoint: 32,
    nullifier_epoch_length: 32,
    max_historical_nullifier_batch: 512,
    archive_shard_epoch_span: 16,
    archive_provider_replica_count: 4,
    archive_segment_target_providers: 3,
    archive_checkpoint_packet_segments: 4,
    archive_checkpoint_stratum_packets: 4,
    archive_retention_horizon_epochs: 256,
    oblivious_sync_min_batch: 4,
    oblivious_sync_refresh_interval_secs: 300,
    oblivious_sync_cover_queries: 4,
};
