#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProtocolRules {
    pub version: u32,
    pub shielded_pool_version: u8,
    pub max_active_validators: u16,
    pub slots_per_epoch: u32,
    pub slot_duration_ms: u64,
    pub fast_path_timeout_ms: u64,
    pub dag_bft_timeout_ms: u64,
    pub max_coins_per_epoch: u32,
    pub nullifier_epoch_length: u64,
    pub max_historical_nullifier_batch: u32,
    pub archive_shard_epoch_span: u64,
    pub archive_provider_replica_count: u32,
    pub archive_segment_target_providers: u32,
    pub archive_checkpoint_packet_segments: u32,
    pub archive_checkpoint_stratum_packets: u32,
    pub archive_retention_horizon_epochs: u64,
    pub oblivious_sync_min_batch: u32,
    pub oblivious_sync_refresh_interval_secs: u64,
    pub oblivious_sync_cover_queries: u32,
}

pub const CURRENT: ProtocolRules = ProtocolRules {
    version: 1,
    shielded_pool_version: 1,
    max_active_validators: 32,
    slots_per_epoch: 256,
    slot_duration_ms: 250,
    fast_path_timeout_ms: 450,
    dag_bft_timeout_ms: 1_200,
    max_coins_per_epoch: 111,
    nullifier_epoch_length: 32,
    max_historical_nullifier_batch: 512,
    archive_shard_epoch_span: 16,
    archive_provider_replica_count: 4,
    archive_segment_target_providers: 3,
    archive_checkpoint_packet_segments: 4,
    archive_checkpoint_stratum_packets: 4,
    archive_retention_horizon_epochs: 256,
    oblivious_sync_min_batch: 4,
    oblivious_sync_refresh_interval_secs: 300,
    oblivious_sync_cover_queries: 4,
};
